# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bootstrap_prepare_groups_cpp <- function(group) {
    .Call(`_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp`, group)
}

bootstrap_sample_indices_cpp <- function(group_info) {
    .Call(`_DIDmultiplegtDYN_bootstrap_sample_indices_cpp`, group_info)
}

