// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cummax_by_group_cpp
IntegerVector cummax_by_group_cpp(IntegerVector x, IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_cummax_by_group_cpp(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(cummax_by_group_cpp(x, group));
    return rcpp_result_gen;
END_RCPP
}
// compute_var_covar_matrix_cpp
NumericMatrix compute_var_covar_matrix_cpp(NumericMatrix U_Gg_vars, IntegerVector first_obs, int l_XX, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_var_covar_matrix_cpp(SEXP U_Gg_varsSEXP, SEXP first_obsSEXP, SEXP l_XXSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars(U_Gg_varsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_var_covar_matrix_cpp(U_Gg_vars, first_obs, l_XX, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_U_Gg_global_cpp
NumericVector compute_U_Gg_global_cpp(NumericVector U_Gg_plus, NumericVector U_Gg_minus, double N1_weight, double N0_weight);
RcppExport SEXP _DIDmultiplegtDYN_compute_U_Gg_global_cpp(SEXP U_Gg_plusSEXP, SEXP U_Gg_minusSEXP, SEXP N1_weightSEXP, SEXP N0_weightSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_plus(U_Gg_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_minus(U_Gg_minusSEXP);
    Rcpp::traits::input_parameter< double >::type N1_weight(N1_weightSEXP);
    Rcpp::traits::input_parameter< double >::type N0_weight(N0_weightSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_U_Gg_global_cpp(U_Gg_plus, U_Gg_minus, N1_weight, N0_weight));
    return rcpp_result_gen;
END_RCPP
}
// compute_clustered_variance_cpp
List compute_clustered_variance_cpp(NumericVector U_Gg_var, IntegerVector first_obs_gp, IntegerVector first_obs_clust, IntegerVector cluster, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_clustered_variance_cpp(SEXP U_Gg_varSEXP, SEXP first_obs_gpSEXP, SEXP first_obs_clustSEXP, SEXP clusterSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_var(U_Gg_varSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_gp(first_obs_gpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_clust(first_obs_clustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster(clusterSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_clustered_variance_cpp(U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// propagate_treatment_change_cpp
NumericVector propagate_treatment_change_cpp(NumericVector ever_change, IntegerVector group, IntegerVector time, int T_max);
RcppExport SEXP _DIDmultiplegtDYN_propagate_treatment_change_cpp(SEXP ever_changeSEXP, SEXP groupSEXP, SEXP timeSEXP, SEXP T_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ever_change(ever_changeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< int >::type T_max(T_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(propagate_treatment_change_cpp(ever_change, group, time, T_max));
    return rcpp_result_gen;
END_RCPP
}
// initialize_effect_columns_cpp
NumericMatrix initialize_effect_columns_cpp(int nrow, int l_XX, bool include_placebo);
RcppExport SEXP _DIDmultiplegtDYN_initialize_effect_columns_cpp(SEXP nrowSEXP, SEXP l_XXSEXP, SEXP include_placeboSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nrow(nrowSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    Rcpp::traits::input_parameter< bool >::type include_placebo(include_placeboSEXP);
    rcpp_result_gen = Rcpp::wrap(initialize_effect_columns_cpp(nrow, l_XX, include_placebo));
    return rcpp_result_gen;
END_RCPP
}
// compute_weighted_sum_cpp
double compute_weighted_sum_cpp(NumericVector x, IntegerVector mask);
RcppExport SEXP _DIDmultiplegtDYN_compute_weighted_sum_cpp(SEXP xSEXP, SEXP maskSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type mask(maskSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_weighted_sum_cpp(x, mask));
    return rcpp_result_gen;
END_RCPP
}
// compute_delta_D_g_cpp
NumericVector compute_delta_D_g_cpp(NumericMatrix delta_plus, NumericMatrix delta_minus, IntegerVector switchers_tag, int l_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_delta_D_g_cpp(SEXP delta_plusSEXP, SEXP delta_minusSEXP, SEXP switchers_tagSEXP, SEXP l_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type delta_plus(delta_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type delta_minus(delta_minusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type switchers_tag(switchers_tagSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_delta_D_g_cpp(delta_plus, delta_minus, switchers_tag, l_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_full_vcov_cpp
List compute_full_vcov_cpp(NumericMatrix U_Gg_vars_effects, NumericMatrix U_Gg_vars_placebos, IntegerVector first_obs, NumericVector se_effects, NumericVector se_placebos, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_full_vcov_cpp(SEXP U_Gg_vars_effectsSEXP, SEXP U_Gg_vars_placebosSEXP, SEXP first_obsSEXP, SEXP se_effectsSEXP, SEXP se_placebosSEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars_effects(U_Gg_vars_effectsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_vars_placebos(U_Gg_vars_placebosSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se_effects(se_effectsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se_placebos(se_placebosSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_full_vcov_cpp(U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// lag_diff_by_group_cpp
NumericVector lag_diff_by_group_cpp(NumericVector x, IntegerVector group, int lag_periods);
RcppExport SEXP _DIDmultiplegtDYN_lag_diff_by_group_cpp(SEXP xSEXP, SEXP groupSEXP, SEXP lag_periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type lag_periods(lag_periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(lag_diff_by_group_cpp(x, group, lag_periods));
    return rcpp_result_gen;
END_RCPP
}
// shift_by_group_cpp
NumericVector shift_by_group_cpp(NumericVector x, IntegerVector group, int periods);
RcppExport SEXP _DIDmultiplegtDYN_shift_by_group_cpp(SEXP xSEXP, SEXP groupSEXP, SEXP periodsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type periods(periodsSEXP);
    rcpp_result_gen = Rcpp::wrap(shift_by_group_cpp(x, group, periods));
    return rcpp_result_gen;
END_RCPP
}
// conditional_sum_by_group_cpp
NumericVector conditional_sum_by_group_cpp(NumericVector x, IntegerVector condition, IntegerVector group1, IntegerVector group2, Nullable<IntegerVector> group3_);
RcppExport SEXP _DIDmultiplegtDYN_conditional_sum_by_group_cpp(SEXP xSEXP, SEXP conditionSEXP, SEXP group1SEXP, SEXP group2SEXP, SEXP group3_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type condition(conditionSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group1(group1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group2(group2SEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type group3_(group3_SEXP);
    rcpp_result_gen = Rcpp::wrap(conditional_sum_by_group_cpp(x, condition, group1, group2, group3_));
    return rcpp_result_gen;
END_RCPP
}
// sum_by_group_cpp
NumericVector sum_by_group_cpp(NumericVector x, IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_sum_by_group_cpp(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(sum_by_group_cpp(x, group));
    return rcpp_result_gen;
END_RCPP
}
// mean_by_group_cpp
NumericVector mean_by_group_cpp(NumericVector x, IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_mean_by_group_cpp(SEXP xSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_by_group_cpp(x, group));
    return rcpp_result_gen;
END_RCPP
}
// compute_U_Gg_core_cpp
List compute_U_Gg_core_cpp(NumericVector diff_y, NumericVector distance_to_switch, NumericVector N_t_g, NumericVector N_gt_control, NumericVector never_change, NumericVector N_gt, IntegerVector time_XX, NumericVector T_g, IntegerVector group, IntegerVector first_obs, double G_XX, double N_inc, int i, int t_min, int T_max);
RcppExport SEXP _DIDmultiplegtDYN_compute_U_Gg_core_cpp(SEXP diff_ySEXP, SEXP distance_to_switchSEXP, SEXP N_t_gSEXP, SEXP N_gt_controlSEXP, SEXP never_changeSEXP, SEXP N_gtSEXP, SEXP time_XXSEXP, SEXP T_gSEXP, SEXP groupSEXP, SEXP first_obsSEXP, SEXP G_XXSEXP, SEXP N_incSEXP, SEXP iSEXP, SEXP t_minSEXP, SEXP T_maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type diff_y(diff_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distance_to_switch(distance_to_switchSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_t_g(N_t_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt_control(N_gt_controlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type never_change(never_changeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_XX(time_XXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T_g(T_gSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< double >::type N_inc(N_incSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type t_min(t_minSEXP);
    Rcpp::traits::input_parameter< int >::type T_max(T_maxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_U_Gg_core_cpp(diff_y, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, group, first_obs, G_XX, N_inc, i, t_min, T_max));
    return rcpp_result_gen;
END_RCPP
}
// compute_U_Gg_var_temp_cpp
NumericVector compute_U_Gg_var_temp_cpp(NumericVector diff_y, NumericVector E_hat_gt, NumericVector DOF_gt, NumericVector distance_to_switch, NumericVector N_t_g, NumericVector N_gt_control, NumericVector never_change, NumericVector N_gt, IntegerVector time_XX, NumericVector T_g, double G_XX, double N_inc, int i);
RcppExport SEXP _DIDmultiplegtDYN_compute_U_Gg_var_temp_cpp(SEXP diff_ySEXP, SEXP E_hat_gtSEXP, SEXP DOF_gtSEXP, SEXP distance_to_switchSEXP, SEXP N_t_gSEXP, SEXP N_gt_controlSEXP, SEXP never_changeSEXP, SEXP N_gtSEXP, SEXP time_XXSEXP, SEXP T_gSEXP, SEXP G_XXSEXP, SEXP N_incSEXP, SEXP iSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type diff_y(diff_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type E_hat_gt(E_hat_gtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DOF_gt(DOF_gtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type distance_to_switch(distance_to_switchSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_t_g(N_t_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt_control(N_gt_controlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type never_change(never_changeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time_XX(time_XXSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type T_g(T_gSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< double >::type N_inc(N_incSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_U_Gg_var_temp_cpp(diff_y, E_hat_gt, DOF_gt, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, G_XX, N_inc, i));
    return rcpp_result_gen;
END_RCPP
}
// compute_dof_indicator_cpp
IntegerVector compute_dof_indicator_cpp(NumericVector N_gt, NumericVector diff_y, NumericVector never_change, NumericVector N_t, int indicator_type);
RcppExport SEXP _DIDmultiplegtDYN_compute_dof_indicator_cpp(SEXP N_gtSEXP, SEXP diff_ySEXP, SEXP never_changeSEXP, SEXP N_tSEXP, SEXP indicator_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type diff_y(diff_ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type never_change(never_changeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_t(N_tSEXP);
    Rcpp::traits::input_parameter< int >::type indicator_type(indicator_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_dof_indicator_cpp(N_gt, diff_y, never_change, N_t, indicator_type));
    return rcpp_result_gen;
END_RCPP
}
// compute_cohort_mean_cpp
NumericVector compute_cohort_mean_cpp(NumericVector values, NumericVector weights, IntegerVector dof_indicator, IntegerVector group1, IntegerVector group2, Nullable<IntegerVector> group3_);
RcppExport SEXP _DIDmultiplegtDYN_compute_cohort_mean_cpp(SEXP valuesSEXP, SEXP weightsSEXP, SEXP dof_indicatorSEXP, SEXP group1SEXP, SEXP group2SEXP, SEXP group3_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dof_indicator(dof_indicatorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group1(group1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group2(group2SEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type group3_(group3_SEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cohort_mean_cpp(values, weights, dof_indicator, group1, group2, group3_));
    return rcpp_result_gen;
END_RCPP
}
// count_unique_by_group_cpp
IntegerVector count_unique_by_group_cpp(IntegerVector values, IntegerVector dof_indicator, IntegerVector group1, IntegerVector group2, Nullable<IntegerVector> group3_);
RcppExport SEXP _DIDmultiplegtDYN_count_unique_by_group_cpp(SEXP valuesSEXP, SEXP dof_indicatorSEXP, SEXP group1SEXP, SEXP group2SEXP, SEXP group3_SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type values(valuesSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type dof_indicator(dof_indicatorSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group1(group1SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group2(group2SEXP);
    Rcpp::traits::input_parameter< Nullable<IntegerVector> >::type group3_(group3_SEXP);
    rcpp_result_gen = Rcpp::wrap(count_unique_by_group_cpp(values, dof_indicator, group1, group2, group3_));
    return rcpp_result_gen;
END_RCPP
}
// compute_all_effects_cpp
List compute_all_effects_cpp(NumericMatrix U_Gg_plus, NumericMatrix U_Gg_minus, NumericMatrix count_plus, NumericMatrix count_minus, NumericVector N1_vec, NumericVector N0_vec, IntegerVector first_obs_by_gp, double G_XX, int l_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_all_effects_cpp(SEXP U_Gg_plusSEXP, SEXP U_Gg_minusSEXP, SEXP count_plusSEXP, SEXP count_minusSEXP, SEXP N1_vecSEXP, SEXP N0_vecSEXP, SEXP first_obs_by_gpSEXP, SEXP G_XXSEXP, SEXP l_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_plus(U_Gg_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_minus(U_Gg_minusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type count_plus(count_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type count_minus(count_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N1_vec(N1_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N0_vec(N0_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_gp(first_obs_by_gpSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_all_effects_cpp(U_Gg_plus, U_Gg_minus, count_plus, count_minus, N1_vec, N0_vec, first_obs_by_gp, G_XX, l_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_all_variances_cpp
List compute_all_variances_cpp(NumericMatrix U_Gg_var_in, NumericMatrix U_Gg_var_out, NumericVector N1_vec, NumericVector N0_vec, IntegerVector first_obs_by_gp, IntegerVector first_obs_by_clust, IntegerVector cluster_XX, double G_XX, int l_XX, bool clustered);
RcppExport SEXP _DIDmultiplegtDYN_compute_all_variances_cpp(SEXP U_Gg_var_inSEXP, SEXP U_Gg_var_outSEXP, SEXP N1_vecSEXP, SEXP N0_vecSEXP, SEXP first_obs_by_gpSEXP, SEXP first_obs_by_clustSEXP, SEXP cluster_XXSEXP, SEXP G_XXSEXP, SEXP l_XXSEXP, SEXP clusteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_var_in(U_Gg_var_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_var_out(U_Gg_var_outSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N1_vec(N1_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N0_vec(N0_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_gp(first_obs_by_gpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_clust(first_obs_by_clustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_XX(cluster_XXSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< int >::type l_XX(l_XXSEXP);
    Rcpp::traits::input_parameter< bool >::type clustered(clusteredSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_all_variances_cpp(U_Gg_var_in, U_Gg_var_out, N1_vec, N0_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_XX, clustered));
    return rcpp_result_gen;
END_RCPP
}
// compute_placebo_effects_and_variances_cpp
List compute_placebo_effects_and_variances_cpp(NumericMatrix U_Gg_pl_plus, NumericMatrix U_Gg_pl_minus, NumericMatrix count_pl_plus, NumericMatrix count_pl_minus, NumericMatrix U_Gg_var_pl_in, NumericMatrix U_Gg_var_pl_out, NumericVector N1_pl_vec, NumericVector N0_pl_vec, IntegerVector first_obs_by_gp, IntegerVector first_obs_by_clust, IntegerVector cluster_XX, double G_XX, int l_placebo_XX, bool clustered);
RcppExport SEXP _DIDmultiplegtDYN_compute_placebo_effects_and_variances_cpp(SEXP U_Gg_pl_plusSEXP, SEXP U_Gg_pl_minusSEXP, SEXP count_pl_plusSEXP, SEXP count_pl_minusSEXP, SEXP U_Gg_var_pl_inSEXP, SEXP U_Gg_var_pl_outSEXP, SEXP N1_pl_vecSEXP, SEXP N0_pl_vecSEXP, SEXP first_obs_by_gpSEXP, SEXP first_obs_by_clustSEXP, SEXP cluster_XXSEXP, SEXP G_XXSEXP, SEXP l_placebo_XXSEXP, SEXP clusteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_pl_plus(U_Gg_pl_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_pl_minus(U_Gg_pl_minusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type count_pl_plus(count_pl_plusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type count_pl_minus(count_pl_minusSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_var_pl_in(U_Gg_var_pl_inSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_var_pl_out(U_Gg_var_pl_outSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N1_pl_vec(N1_pl_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N0_pl_vec(N0_pl_vecSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_gp(first_obs_by_gpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_clust(first_obs_by_clustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_XX(cluster_XXSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< int >::type l_placebo_XX(l_placebo_XXSEXP);
    Rcpp::traits::input_parameter< bool >::type clustered(clusteredSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_placebo_effects_and_variances_cpp(U_Gg_pl_plus, U_Gg_pl_minus, count_pl_plus, count_pl_minus, U_Gg_var_pl_in, U_Gg_var_pl_out, N1_pl_vec, N0_pl_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_placebo_XX, clustered));
    return rcpp_result_gen;
END_RCPP
}
// compute_vcov_full_cpp
NumericMatrix compute_vcov_full_cpp(NumericMatrix U_Gg_var_glob, IntegerVector first_obs, NumericVector se_vec, bool normalized, Nullable<NumericVector> delta_D_global_, double G_XX);
RcppExport SEXP _DIDmultiplegtDYN_compute_vcov_full_cpp(SEXP U_Gg_var_globSEXP, SEXP first_obsSEXP, SEXP se_vecSEXP, SEXP normalizedSEXP, SEXP delta_D_global_SEXP, SEXP G_XXSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type U_Gg_var_glob(U_Gg_var_globSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs(first_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type se_vec(se_vecSEXP);
    Rcpp::traits::input_parameter< bool >::type normalized(normalizedSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type delta_D_global_(delta_D_global_SEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_vcov_full_cpp(U_Gg_var_glob, first_obs, se_vec, normalized, delta_D_global_, G_XX));
    return rcpp_result_gen;
END_RCPP
}
// compute_avg_effect_cpp
List compute_avg_effect_cpp(NumericVector U_Gg_plus, NumericVector U_Gg_minus, NumericVector U_Gg_var_plus, NumericVector U_Gg_var_minus, IntegerVector first_obs_by_gp, IntegerVector first_obs_by_clust, IntegerVector cluster_XX, double w_plus, double G_XX, bool clustered);
RcppExport SEXP _DIDmultiplegtDYN_compute_avg_effect_cpp(SEXP U_Gg_plusSEXP, SEXP U_Gg_minusSEXP, SEXP U_Gg_var_plusSEXP, SEXP U_Gg_var_minusSEXP, SEXP first_obs_by_gpSEXP, SEXP first_obs_by_clustSEXP, SEXP cluster_XXSEXP, SEXP w_plusSEXP, SEXP G_XXSEXP, SEXP clusteredSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_plus(U_Gg_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_minus(U_Gg_minusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_var_plus(U_Gg_var_plusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type U_Gg_var_minus(U_Gg_var_minusSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_gp(first_obs_by_gpSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type first_obs_by_clust(first_obs_by_clustSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type cluster_XX(cluster_XXSEXP);
    Rcpp::traits::input_parameter< double >::type w_plus(w_plusSEXP);
    Rcpp::traits::input_parameter< double >::type G_XX(G_XXSEXP);
    Rcpp::traits::input_parameter< bool >::type clustered(clusteredSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_avg_effect_cpp(U_Gg_plus, U_Gg_minus, U_Gg_var_plus, U_Gg_var_minus, first_obs_by_gp, first_obs_by_clust, cluster_XX, w_plus, G_XX, clustered));
    return rcpp_result_gen;
END_RCPP
}
// same_switchers_loop_cpp
List same_switchers_loop_cpp(NumericVector outcome, IntegerVector group, IntegerVector time, NumericVector F_g, NumericVector N_gt, IntegerVector d_sq, int effects, int T_max, bool only_never_switchers);
RcppExport SEXP _DIDmultiplegtDYN_same_switchers_loop_cpp(SEXP outcomeSEXP, SEXP groupSEXP, SEXP timeSEXP, SEXP F_gSEXP, SEXP N_gtSEXP, SEXP d_sqSEXP, SEXP effectsSEXP, SEXP T_maxSEXP, SEXP only_never_switchersSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type outcome(outcomeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type F_g(F_gSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type N_gt(N_gtSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d_sq(d_sqSEXP);
    Rcpp::traits::input_parameter< int >::type effects(effectsSEXP);
    Rcpp::traits::input_parameter< int >::type T_max(T_maxSEXP);
    Rcpp::traits::input_parameter< bool >::type only_never_switchers(only_never_switchersSEXP);
    rcpp_result_gen = Rcpp::wrap(same_switchers_loop_cpp(outcome, group, time, F_g, N_gt, d_sq, effects, T_max, only_never_switchers));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_prepare_groups_cpp
List bootstrap_prepare_groups_cpp(IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_prepare_groups_cpp(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_prepare_groups_cpp(group));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_sample_indices_cpp
IntegerVector bootstrap_sample_indices_cpp(List group_info);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_sample_indices_cpp(SEXP group_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type group_info(group_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_sample_indices_cpp(group_info));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_compute_sd_cpp
NumericVector bootstrap_compute_sd_cpp(NumericMatrix results);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_compute_sd_cpp(SEXP resultsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type results(resultsSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_compute_sd_cpp(results));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_extract_results_cpp
NumericMatrix bootstrap_extract_results_cpp(List results_list, int n_bootstrap, int n_effects);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_extract_results_cpp(SEXP results_listSEXP, SEXP n_bootstrapSEXP, SEXP n_effectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type results_list(results_listSEXP);
    Rcpp::traits::input_parameter< int >::type n_bootstrap(n_bootstrapSEXP);
    Rcpp::traits::input_parameter< int >::type n_effects(n_effectsSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_extract_results_cpp(results_list, n_bootstrap, n_effects));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_compute_ci_cpp
List bootstrap_compute_ci_cpp(NumericVector estimates, NumericVector sd_vec, double ci_level);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_compute_ci_cpp(SEXP estimatesSEXP, SEXP sd_vecSEXP, SEXP ci_levelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type estimates(estimatesSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type sd_vec(sd_vecSEXP);
    Rcpp::traits::input_parameter< double >::type ci_level(ci_levelSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_compute_ci_cpp(estimates, sd_vec, ci_level));
    return rcpp_result_gen;
END_RCPP
}
// compute_Tg_cpp
NumericVector compute_Tg_cpp(IntegerVector G, IntegerVector Tvec, NumericVector Y, NumericVector F_vec, NumericVector TGC, IntegerVector EV, IntegerVector CLS, IntegerVector NGT);
RcppExport SEXP _DIDmultiplegtDYN_compute_Tg_cpp(SEXP GSEXP, SEXP TvecSEXP, SEXP YSEXP, SEXP F_vecSEXP, SEXP TGCSEXP, SEXP EVSEXP, SEXP CLSSEXP, SEXP NGTSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type G(GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Tvec(TvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type F_vec(F_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type TGC(TGCSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type EV(EVSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type CLS(CLSSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NGT(NGTSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_Tg_cpp(G, Tvec, Y, F_vec, TGC, EV, CLS, NGT));
    return rcpp_result_gen;
END_RCPP
}
// avg_cumul_cpp
List avg_cumul_cpp(IntegerVector G, IntegerVector Tvec, NumericVector D, NumericVector Y, NumericVector D1, NumericVector F_vec, NumericVector Tg_ph, IntegerVector EV, IntegerVector CLS, NumericVector Mg_ph, IntegerVector NGT, NumericVector SG, NumericVector W, int ell, int ssw_flag, std::string sw_dir);
RcppExport SEXP _DIDmultiplegtDYN_avg_cumul_cpp(SEXP GSEXP, SEXP TvecSEXP, SEXP DSEXP, SEXP YSEXP, SEXP D1SEXP, SEXP F_vecSEXP, SEXP Tg_phSEXP, SEXP EVSEXP, SEXP CLSSEXP, SEXP Mg_phSEXP, SEXP NGTSEXP, SEXP SGSEXP, SEXP WSEXP, SEXP ellSEXP, SEXP ssw_flagSEXP, SEXP sw_dirSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type G(GSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type Tvec(TvecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type D1(D1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type F_vec(F_vecSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Tg_ph(Tg_phSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type EV(EVSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type CLS(CLSSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Mg_ph(Mg_phSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type NGT(NGTSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type SG(SGSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type W(WSEXP);
    Rcpp::traits::input_parameter< int >::type ell(ellSEXP);
    Rcpp::traits::input_parameter< int >::type ssw_flag(ssw_flagSEXP);
    Rcpp::traits::input_parameter< std::string >::type sw_dir(sw_dirSEXP);
    rcpp_result_gen = Rcpp::wrap(avg_cumul_cpp(G, Tvec, D, Y, D1, F_vec, Tg_ph, EV, CLS, Mg_ph, NGT, SG, W, ell, ssw_flag, sw_dir));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DIDmultiplegtDYN_cummax_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_cummax_by_group_cpp, 2},
    {"_DIDmultiplegtDYN_compute_var_covar_matrix_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_var_covar_matrix_cpp, 4},
    {"_DIDmultiplegtDYN_compute_U_Gg_global_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_U_Gg_global_cpp, 4},
    {"_DIDmultiplegtDYN_compute_clustered_variance_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_clustered_variance_cpp, 5},
    {"_DIDmultiplegtDYN_propagate_treatment_change_cpp", (DL_FUNC) &_DIDmultiplegtDYN_propagate_treatment_change_cpp, 4},
    {"_DIDmultiplegtDYN_initialize_effect_columns_cpp", (DL_FUNC) &_DIDmultiplegtDYN_initialize_effect_columns_cpp, 3},
    {"_DIDmultiplegtDYN_compute_weighted_sum_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_weighted_sum_cpp, 2},
    {"_DIDmultiplegtDYN_compute_delta_D_g_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_delta_D_g_cpp, 4},
    {"_DIDmultiplegtDYN_compute_full_vcov_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_full_vcov_cpp, 6},
    {"_DIDmultiplegtDYN_lag_diff_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_lag_diff_by_group_cpp, 3},
    {"_DIDmultiplegtDYN_shift_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_shift_by_group_cpp, 3},
    {"_DIDmultiplegtDYN_conditional_sum_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_conditional_sum_by_group_cpp, 5},
    {"_DIDmultiplegtDYN_sum_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_sum_by_group_cpp, 2},
    {"_DIDmultiplegtDYN_mean_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_mean_by_group_cpp, 2},
    {"_DIDmultiplegtDYN_compute_U_Gg_core_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_U_Gg_core_cpp, 15},
    {"_DIDmultiplegtDYN_compute_U_Gg_var_temp_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_U_Gg_var_temp_cpp, 13},
    {"_DIDmultiplegtDYN_compute_dof_indicator_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_dof_indicator_cpp, 5},
    {"_DIDmultiplegtDYN_compute_cohort_mean_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_cohort_mean_cpp, 6},
    {"_DIDmultiplegtDYN_count_unique_by_group_cpp", (DL_FUNC) &_DIDmultiplegtDYN_count_unique_by_group_cpp, 5},
    {"_DIDmultiplegtDYN_compute_all_effects_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_all_effects_cpp, 9},
    {"_DIDmultiplegtDYN_compute_all_variances_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_all_variances_cpp, 10},
    {"_DIDmultiplegtDYN_compute_placebo_effects_and_variances_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_placebo_effects_and_variances_cpp, 14},
    {"_DIDmultiplegtDYN_compute_vcov_full_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_vcov_full_cpp, 6},
    {"_DIDmultiplegtDYN_compute_avg_effect_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_avg_effect_cpp, 10},
    {"_DIDmultiplegtDYN_same_switchers_loop_cpp", (DL_FUNC) &_DIDmultiplegtDYN_same_switchers_loop_cpp, 9},
    {"_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp, 1},
    {"_DIDmultiplegtDYN_bootstrap_sample_indices_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_sample_indices_cpp, 1},
    {"_DIDmultiplegtDYN_bootstrap_compute_sd_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_compute_sd_cpp, 1},
    {"_DIDmultiplegtDYN_bootstrap_extract_results_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_extract_results_cpp, 3},
    {"_DIDmultiplegtDYN_bootstrap_compute_ci_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_compute_ci_cpp, 3},
    {"_DIDmultiplegtDYN_compute_Tg_cpp", (DL_FUNC) &_DIDmultiplegtDYN_compute_Tg_cpp, 8},
    {"_DIDmultiplegtDYN_avg_cumul_cpp", (DL_FUNC) &_DIDmultiplegtDYN_avg_cumul_cpp, 16},
    {NULL, NULL, 0}
};

RcppExport void R_init_DIDmultiplegtDYN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
