// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// bootstrap_prepare_groups_cpp
List bootstrap_prepare_groups_cpp(IntegerVector group);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_prepare_groups_cpp(SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_prepare_groups_cpp(group));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_sample_indices_cpp
IntegerVector bootstrap_sample_indices_cpp(List group_info);
RcppExport SEXP _DIDmultiplegtDYN_bootstrap_sample_indices_cpp(SEXP group_infoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type group_info(group_infoSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_sample_indices_cpp(group_info));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp, 1},
    {"_DIDmultiplegtDYN_bootstrap_sample_indices_cpp", (DL_FUNC) &_DIDmultiplegtDYN_bootstrap_sample_indices_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_DIDmultiplegtDYN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
