# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cummax_by_group_cpp <- function(x, group) {
    .Call(`_DIDmultiplegtDYN_cummax_by_group_cpp`, x, group)
}

compute_var_covar_matrix_cpp <- function(U_Gg_vars, first_obs, l_XX, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_var_covar_matrix_cpp`, U_Gg_vars, first_obs, l_XX, G_XX)
}

compute_U_Gg_global_cpp <- function(U_Gg_plus, U_Gg_minus, N1_weight, N0_weight) {
    .Call(`_DIDmultiplegtDYN_compute_U_Gg_global_cpp`, U_Gg_plus, U_Gg_minus, N1_weight, N0_weight)
}

compute_clustered_variance_cpp <- function(U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_clustered_variance_cpp`, U_Gg_var, first_obs_gp, first_obs_clust, cluster, G_XX)
}

propagate_treatment_change_cpp <- function(ever_change, group, time, T_max) {
    .Call(`_DIDmultiplegtDYN_propagate_treatment_change_cpp`, ever_change, group, time, T_max)
}

initialize_effect_columns_cpp <- function(nrow, l_XX, include_placebo) {
    .Call(`_DIDmultiplegtDYN_initialize_effect_columns_cpp`, nrow, l_XX, include_placebo)
}

compute_weighted_sum_cpp <- function(x, mask) {
    .Call(`_DIDmultiplegtDYN_compute_weighted_sum_cpp`, x, mask)
}

compute_delta_D_g_cpp <- function(delta_plus, delta_minus, switchers_tag, l_XX) {
    .Call(`_DIDmultiplegtDYN_compute_delta_D_g_cpp`, delta_plus, delta_minus, switchers_tag, l_XX)
}

compute_full_vcov_cpp <- function(U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX) {
    .Call(`_DIDmultiplegtDYN_compute_full_vcov_cpp`, U_Gg_vars_effects, U_Gg_vars_placebos, first_obs, se_effects, se_placebos, G_XX)
}

lag_diff_by_group_cpp <- function(x, group, lag_periods) {
    .Call(`_DIDmultiplegtDYN_lag_diff_by_group_cpp`, x, group, lag_periods)
}

shift_by_group_cpp <- function(x, group, periods) {
    .Call(`_DIDmultiplegtDYN_shift_by_group_cpp`, x, group, periods)
}

conditional_sum_by_group_cpp <- function(x, condition, group1, group2, group3_ = NULL) {
    .Call(`_DIDmultiplegtDYN_conditional_sum_by_group_cpp`, x, condition, group1, group2, group3_)
}

sum_by_group_cpp <- function(x, group) {
    .Call(`_DIDmultiplegtDYN_sum_by_group_cpp`, x, group)
}

mean_by_group_cpp <- function(x, group) {
    .Call(`_DIDmultiplegtDYN_mean_by_group_cpp`, x, group)
}

compute_U_Gg_core_cpp <- function(diff_y, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, group, first_obs, G_XX, N_inc, i, t_min, T_max) {
    .Call(`_DIDmultiplegtDYN_compute_U_Gg_core_cpp`, diff_y, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, group, first_obs, G_XX, N_inc, i, t_min, T_max)
}

compute_U_Gg_var_temp_cpp <- function(diff_y, E_hat_gt, DOF_gt, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, G_XX, N_inc, i) {
    .Call(`_DIDmultiplegtDYN_compute_U_Gg_var_temp_cpp`, diff_y, E_hat_gt, DOF_gt, distance_to_switch, N_t_g, N_gt_control, never_change, N_gt, time_XX, T_g, G_XX, N_inc, i)
}

compute_dof_indicator_cpp <- function(N_gt, diff_y, never_change, N_t, indicator_type) {
    .Call(`_DIDmultiplegtDYN_compute_dof_indicator_cpp`, N_gt, diff_y, never_change, N_t, indicator_type)
}

compute_cohort_mean_cpp <- function(values, weights, dof_indicator, group1, group2, group3_ = NULL) {
    .Call(`_DIDmultiplegtDYN_compute_cohort_mean_cpp`, values, weights, dof_indicator, group1, group2, group3_)
}

count_unique_by_group_cpp <- function(values, dof_indicator, group1, group2, group3_ = NULL) {
    .Call(`_DIDmultiplegtDYN_count_unique_by_group_cpp`, values, dof_indicator, group1, group2, group3_)
}

compute_all_effects_cpp <- function(U_Gg_plus, U_Gg_minus, count_plus, count_minus, N1_vec, N0_vec, first_obs_by_gp, G_XX, l_XX) {
    .Call(`_DIDmultiplegtDYN_compute_all_effects_cpp`, U_Gg_plus, U_Gg_minus, count_plus, count_minus, N1_vec, N0_vec, first_obs_by_gp, G_XX, l_XX)
}

compute_all_variances_cpp <- function(U_Gg_var_in, U_Gg_var_out, N1_vec, N0_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_XX, clustered) {
    .Call(`_DIDmultiplegtDYN_compute_all_variances_cpp`, U_Gg_var_in, U_Gg_var_out, N1_vec, N0_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_XX, clustered)
}

compute_placebo_effects_and_variances_cpp <- function(U_Gg_pl_plus, U_Gg_pl_minus, count_pl_plus, count_pl_minus, U_Gg_var_pl_in, U_Gg_var_pl_out, N1_pl_vec, N0_pl_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_placebo_XX, clustered) {
    .Call(`_DIDmultiplegtDYN_compute_placebo_effects_and_variances_cpp`, U_Gg_pl_plus, U_Gg_pl_minus, count_pl_plus, count_pl_minus, U_Gg_var_pl_in, U_Gg_var_pl_out, N1_pl_vec, N0_pl_vec, first_obs_by_gp, first_obs_by_clust, cluster_XX, G_XX, l_placebo_XX, clustered)
}

compute_vcov_full_cpp <- function(U_Gg_var_glob, first_obs, se_vec, normalized, delta_D_global_ = NULL, G_XX = 1.0) {
    .Call(`_DIDmultiplegtDYN_compute_vcov_full_cpp`, U_Gg_var_glob, first_obs, se_vec, normalized, delta_D_global_, G_XX)
}

compute_avg_effect_cpp <- function(U_Gg_plus, U_Gg_minus, U_Gg_var_plus, U_Gg_var_minus, first_obs_by_gp, first_obs_by_clust, cluster_XX, w_plus, G_XX, clustered) {
    .Call(`_DIDmultiplegtDYN_compute_avg_effect_cpp`, U_Gg_plus, U_Gg_minus, U_Gg_var_plus, U_Gg_var_minus, first_obs_by_gp, first_obs_by_clust, cluster_XX, w_plus, G_XX, clustered)
}

same_switchers_loop_cpp <- function(outcome, group, time, F_g, N_gt, d_sq, effects, T_max, only_never_switchers) {
    .Call(`_DIDmultiplegtDYN_same_switchers_loop_cpp`, outcome, group, time, F_g, N_gt, d_sq, effects, T_max, only_never_switchers)
}

bootstrap_prepare_groups_cpp <- function(group) {
    .Call(`_DIDmultiplegtDYN_bootstrap_prepare_groups_cpp`, group)
}

bootstrap_sample_indices_cpp <- function(group_info) {
    .Call(`_DIDmultiplegtDYN_bootstrap_sample_indices_cpp`, group_info)
}

bootstrap_compute_sd_cpp <- function(results) {
    .Call(`_DIDmultiplegtDYN_bootstrap_compute_sd_cpp`, results)
}

bootstrap_extract_results_cpp <- function(results_list, n_bootstrap, n_effects) {
    .Call(`_DIDmultiplegtDYN_bootstrap_extract_results_cpp`, results_list, n_bootstrap, n_effects)
}

bootstrap_compute_ci_cpp <- function(estimates, sd_vec, ci_level) {
    .Call(`_DIDmultiplegtDYN_bootstrap_compute_ci_cpp`, estimates, sd_vec, ci_level)
}

compute_Tg_cpp <- function(G, Tvec, Y, F_vec, TGC, EV, CLS, NGT) {
    .Call(`_DIDmultiplegtDYN_compute_Tg_cpp`, G, Tvec, Y, F_vec, TGC, EV, CLS, NGT)
}

avg_cumul_cpp <- function(G, Tvec, D, Y, D1, F_vec, Tg_ph, EV, CLS, Mg_ph, NGT, SG, W, ell, ssw_flag, sw_dir) {
    .Call(`_DIDmultiplegtDYN_avg_cumul_cpp`, G, Tvec, D, Y, D1, F_vec, Tg_ph, EV, CLS, Mg_ph, NGT, SG, W, ell, ssw_flag, sw_dir)
}

